spring.application.name=demo
data.user-name=amdzak
data.password=123123
spring.main.banner-mode=off

# ROOT severity
logging.level.root=INFO

# servery per package
logging.level.com.example.demo=DEBUG

# pattern layout / format
logging.pattern.console=%d{HH:mm:ss} [%thread{id}] [%-5p] %c{0} - %m%n

#logging to file
#logging.file.name=logs/app-log.log
#location file log
#logging.file.path=./logs
#pattern layout
#logging.pattern.file=%d{HH:mm:ss.SSS} [%-5level] - %msg \\(%logger{0}:%L\\)%n
#logging.logback.rollingpolicy.file-name-pattern=${logging.file.path}/archived/%d{yyyy-MM-dd}.%i.log
#define name log
#logging.file.name=${logging.file.path}/demo1.log
#disable log console
#logging.console.enabled=false
#logging.logback.rollingpolicy.max-history=30
#logging.logback.rollingpolicy.total-size-cap=10MB
